all: ./__init__.py \
	./controllers/appadmin.py \
	./controllers/default.py \
	./languages/ar.py \
	./languages/ca.py \
	./languages/cs.py \
	./languages/de.py \
	./languages/en.py \
	./languages/es.py \
	./languages/fr-ca.py \
	./languages/fr.py \
	./languages/hi.py \
	./languages/hu.py \
	./languages/id.py \
	./languages/it.py \
	./languages/my-mm.py \
	./languages/my.py \
	./languages/nl.py \
	./languages/pl.py \
	./languages/plural-cs.py \
	./languages/plural-en.py \
	./languages/plural-es.py \
	./languages/plural-ru.py \
	./languages/plural-uk.py \
	./languages/pt-br.py \
	./languages/pt.py \
	./languages/ro.py \
	./languages/ru.py \
	./languages/sk.py \
	./languages/tr.py \
	./languages/uk.py \
	./languages/zh-cn.py \
	./languages/zh-tw.py \
	./languages/zh.py \
	./models/db.py \
	./models/menu.py \
	./modules/__init__.py \
	./routes.example.py \
	./views/__init__.py
	@echo "Doing the thing."

